// Flow's personality: a witty Indian friend who knows exactly where your money went and says so.
// One line per day of the year, rotated per user so a whole year passes without a repeat.
// Placeholders: {name} first name, {top} biggest category, {over} amount over the limit (roasts only),
// {streak} days within allowance (praise only), {bro}/{Bro} what Flow calls the user (their nickname, else first name).
// Lines are written gender-neutral: the user is never the subject of a gendered verb (no "tu kar raha/rahi hai");
// use imperatives, "tune … kiya", or make the wallet / expense / Flow the subject instead.

/** What Flow calls the user: the nickname they chose in their profile, otherwise their first name. */
export function displayAddress(nickname?: string | null, name?: string | null) {
  return (nickname ?? "").trim() || (name ?? "").trim().split(/\s+/)[0] || "Boss";
}

/** {bro} and {Bro} for the user's form of address (see displayAddress). */
export function addressVars(address?: string | null) {
  const word = (address ?? "").trim() || "Boss";
  return { bro: word, Bro: word[0].toUpperCase() + word.slice(1) };
}

export const BUDGET_ROASTS = [
  // Spending
  "Kharcha dekh ke Flow ne apna hi budget cut kar diya.",
  "Budget aur tu — do strangers jo ek hi app mein rehte hain.",
  "{Bro}, ye spending nahi, speedrun hai.",
  "Okay genius, is plan ka next step kya hai?",
  "Interesting financial strategy. Bold. Wrong, but bold.",
  "Flow has questions. Bahut saare questions.",
  "Who approved this? Kyunki Flow ne toh nahi kiya.",
  "Explain yourself. Flow wait kar raha hai.",
  "Noted. Judging. Silently. Actually nahi — loudly.",
  "Respectfully... ye kya tha?",
  "Yeah... we're not doing this again, okay?",
  "Be honest — ye zaroorat thi ya mood?",
  "Tera kharcha dekh ke graph ne gym join kar liya. Sirf upar ja raha hai.",
  "Aaj ka spending dekh ke lagta hai kal ka koi plan hi nahi hai.",
  "Paisa aata hai, paisa jaata hai. Tere case mein sirf jaata hai.",
  "Money management level: 'Dekhenge'.",
  "Ye budget tha ya suggestion?",
  "Kharcha itna consistent hai, salary se zyada reliable lagta hai.",
  "Congratulations, tu apne hi budget ka sabse bada risk factor hai.",
  "Is rate pe month-end tak barter system pe aana padega.",
  "Achha hua paise bolte nahi. Warna abhi chilla rahe hote.",
  "Wallet ne 'Do Not Disturb' laga diya hai. Tere liye.",
  "Tera spending pattern: pehle kharcho, phir socho, phir Flow kholo.",
  "Inflation ki personal franchise le li kya?",
  "Aaj ki headline: Local wallet, national level ka kharcha.",
  "Main sirf numbers dikhata hoon. Numbers khud sharminda hain.",
  "'Thoda sa' — ye tune aaj kitni baar bola?",
  "Is speed pe toh budget ko bhi seatbelt chahiye.",

  // Budget overrun
  "{over} over the line. Explain yourself.",
  "{over} extra. Mathematics has left the chat.",
  "{over} upar. Budget ne kaha 'bas', tune suna 'aur'.",
  "{over} over. Flow is not angry. Flow is disappointed.",
  "{over} ka gap. Ye gap nahi, khaai hai.",
  "Budget line cross. {over} ka toll tax bhar diya.",
  "{over} over. Flow ne screenshot le liya hai. Evidence.",
  "{over} upar gaye. Wapas kaun laayega? Hum hi?",
  "Limit: exists. Tu: {over} upar.",
  "{over} over. Budget tha, 'terms and conditions' nahi jo skip kar de.",
  "Budget ne haath jode. Tune {over} aur kharch diye.",
  "{over} upar. Accountant hota toh resign kar deta.",
  "{over} extra. Isko 'investment in happiness' bolein? Nahi.",
  "{over} over. Plan B hai? Plan A bhi tha kya?",
  "{over} over, and the month isn't even tired yet.",
  "{over} upar. Chart laal hai. Tera chehra bhi hona chahiye.",
  "{over} extra. Kal Maggi, parso Maggi, uske baad bhi Maggi.",
  "{over} over. Budget ko ghost mat kar, woh abhi bhi reply kar raha hai.",
  "{over} ki overshooting. Army mein medal milta, yahan sirf Flow ka roast.",
  "Red line: crossed. Margin: {over}. Mood: Flow ka kharab.",
  "{over} upar. Budget ne apna status 'It's complicated' kar diya.",
  "{over} extra. Salary ko aaye kitne din hue the?",

  // Food
  "Order history padh ke lagta hai tu restaurant ka silent partner hai.",
  "Tera favourite dish: 'jo bhi jaldi deliver ho jaaye'.",
  "Swiggy ko tera naam, address aur mood — teeno yaad hain.",
  "Delivery wale bhaiya ab rishtedaar lagte hain. Shaadi mein bulaana padega.",
  "Ghar mein khana hai. Pata hai na?",
  "Fridge khol ke dekh. Wahan bhi khana hota hai. Free mein.",
  "₹400 ki biryani. Mummy ki dal-chawal ne kya bigaada tha?",
  "Tera pet aur tera wallet — dono ka size alag hai. Samajh.",
  "Maggi 2 minute mein banti hai. Budget 2 minute mein doobta hai.",
  "'Bas chai' bol ke ₹300 ka cafe bill. Classic.",
  "Coffee ₹280. Ghar ki chai ₹8. {Bro}, maths.",
  "Raat 1 baje order? Kaunsi emergency thi?",
  "Food app ka 'Reorder' button tera best friend ban gaya hai.",
  "Ye khana order nahi ho raha, restaurants sponsor ho rahe hain.",
  "'Free delivery' ke liye ₹200 ka extra item. Genius move.",
  "Momos ka bill dekh ke Flow ka bhi pet bhar gaya.",
  "Tiffin pack kar le. Paisa bhi bachega, office wale bhi jalenge.",
  "Brunch, lunch, midnight snack — tu food critic hai kya?",
  "Dal-chawal ₹60. Tera order ₹640. Farak: character.",
  "Pizza pe pizza. Budget pe dhakka.",
  "Chef ki salary lagta hai tere hi account se jaati hai.",
  "Khana bhi EMI pe order ho raha hai kya?",
  "Cloud kitchen ka asli cloud tera paisa hai.",

  // Shopping
  "Package aaya, khula, aur yaadon se gayab. Agla package kab?",
  "'Just browsing' ka matlab tere case mein kabhi sirf browsing nahi hota.",
  "Cart full. Bank account empty. Classic combo.",
  "'Add to cart' tera cardio hai. Aur ye workout roz hota hai.",
  "Courier wala tujhe naam se bulata hai. Aur tu proud hai?",
  "Sale thi. Zaroorat nahi thi. Farak samajh.",
  "70% off ka matlab 30% kharcha hai. Zero nahi.",
  "Ek aur t-shirt. Almirah ne complaint file kar di.",
  "Jo cheez 3 din mein yaad bhi nahi rahegi, uske liye 3 hazaar?",
  "Discount ke chakkar mein poori MRP ka dukh.",
  "Ye shopping nahi, dopamine ki kharidari hai. Mehnga wala.",
  "Wishlist → cart → order. Speedrun complete.",
  "Ghar mein itne dabbe hain ki raddi wala ameer ho jayega.",
  "'Only 2 left' dekh ke tera dimaag bhi 2 hi reh jaata hai.",
  "Unboxing ka maza 5 minute. Bill ka dukh poora mahina.",
  "Sneakers pe sneakers. Athlete hai ya collector?",
  "Kyun khareeda? 'Achha laga.' Solid financial reasoning.",
  "Tere orders ki wajah se warehouse wale overtime kar rahe hain.",
  "Return window band hone se pehle ek baar soch le. Please.",
  "Buy 1 Get 1. Tujhe 0 chahiye tha.",
  "Brand ke tag ke liye ₹2000 extra. Tag pehen ke ghoomega?",
  "Big sale roz nahi hoti. Tera kharcha roz hota hai.",
  "Shopping app home screen se hata. Bas suggestion hai.",
  "Mall tera second home nahi. First home hai.",

  // Subscriptions
  "Kisi app ko last kab khola tha? Woh har mahine tujhe yaad karta hai.",
  "Paanch OTT, ek insaan, zero time. Maths nahi baith raha.",
  "Free trial cancel karna tha. Tujhe yaad nahi, Flow ko hai.",
  "Auto-debit ne phir se chupke se hamla kiya.",
  "Gym membership: active. Tu: inactive.",
  "Premium plan liya, use basic se bhi kam.",
  "Teen music apps ka subscription. Kaan do hi hain, {bro}.",
  "Cloud storage full, bank account empty. Balance.",
  "'Cancel anytime.' Tu: 'kabhi nahi.'",
  "Saare subscriptions jod ke dekh — ek chhoti EMI ban gayi hai.",
  "Jo app mahine mein ek baar kholta hai, uska monthly bill kyun?",
  "Annual plan liya 'saving' ke liye. Use kiya 2 din.",
  "Itne streaming apps? Khud ka OTT platform khol liya kya?",
  "Recurring payments ki list padh. Horror movie hai.",
  "Auto-renew: on. Dimaag: off.",
  "Har mahine chupke se kat raha hai. Bas tere radar pe nahi aa raha.",
  "Subscriptions: jitne hain, utne hi yaad se bahar hain.",

  // Impulse spending
  "'Bas dekhna hi toh tha' — famous last words.",
  "Be honest — ye raat 2 baje wala decision tha na?",
  "Impulse buy? Nahi. Impulse lifestyle.",
  "Sochna, khareedna, pachhtana. Teen second mein.",
  "24 ghante ruk ke dekh. Aadhi cheezein khud dimaag se nikal jayengi.",
  "Mood kharab tha, card nikala. Mood theek nahi hua, balance kharab ho gaya.",
  "Boredom ka ilaaj? Kitaab padh le. Sasti bhi hai.",
  "Retail therapy se asli therapy sasti padti.",
  "Ad dekha, click kiya, khareed liya. Algorithm: 1, Tu: 0.",
  "'Recommended for you' ka matlab hai 'budget against you'.",
  "Reel dekhi, product khareeda. Reel real nahi thi.",
  "Influencer ko commission mila. Tujhe? Ek aur dabba.",
  "YOLO bol ke kharcha kiya. Bill bhi YOLO bol ke aayega.",
  "FOMO ka ilaaj shopping nahi hai. Mute button hai.",
  "Khareedne se pehle soch: ye kitne ghante ki mehnat hai?",
  "Checkout page pe ungli rukti kyun nahi?",
  "'I deserve it' — haan. Budget bhi deserve karta hai.",
  "Treat yourself ka matlab roz treat nahi hota.",
  "Tera 'bas ek' kabhi ek nahi hota.",
  "Late night shopping band. Raat ko dimaag half-price pe chalta hai.",
  "Stress mein shopping? Stress bhi gaya nahi, paisa zaroor gaya.",

  // UPI / card
  "UPI history scroll karte karte thumb thak gaya. Flow ka bhi.",
  "UPI ka 'ting' sun ke Flow ka dil 'thak' karta hai.",
  "Scan karna easy hai. Kamaana nahi.",
  "QR code dekhte hi tera haath autopilot pe chala jaata hai.",
  "Credit card free money nahi hai. Bill aata hai. Hamesha.",
  "Credit limit target nahi hai, {bro}. Limit hai.",
  "Minimum due bhar ke khush? Bank bhi khush hai. Byaaj se.",
  "'Buy now, pay later' ka 'later' aa raha hai. Taiyaar reh.",
  "Card itna smooth swipe hota hai, jaise consequences exist hi nahi karte.",
  "Card decline hua? Universe bhi Flow ki side hai.",
  "'Payment successful.' Tera wallet: 'mere liye nahi.'",
  "OTP aaya toh ek second ruk. Wahi second paisa bachata hai.",
  "UPI PIN yaad hai, budget yaad nahi?",
  "₹20 ka cashback, ₹2000 ka kharcha. Great deal. Unke liye.",
  "Reward points se ghar nahi chalta. Try kar liya?",
  "EMI pe EMI. EMIs collect karne ka shauk hai kya?",
  "No-cost EMI. Cost: tera future.",
  "Tap to pay itna fast hai ki sochne ka time hi nahi milta. Wahi toh plan hai.",
  "Bank ka SMS: 'balance low'. Flow ka message: 'told you'.",
  "Card ki limit badhwayi, kharcha bhi badh gaya. Coincidence? Nahi.",
  "Pay Later apps ki list dekh ke Flow ko chakkar aa gaya.",
  "Wallet mein ₹200, dil mein Ambani. Balance kar.",

  // Salary
  "Salary ka SMS aur 'balance low' ka SMS ek hi hafte mein? Record.",
  "Salary aayi, dekhi, chali gayi. Ek hafte mein poori trilogy.",
  "Salary ko account mein thoda rukne de. Mehmaan hai, bhagao mat.",
  "Tere account mein salary aati nahi, transit karti hai.",
  "Mahine ki pehli tareekh: raja. Pandrah tareekh: praja.",
  "Paisa kamaane mein mahina lagta hai. Udaane mein weekend.",
  "Boss ki daant kha ke kamaya paisa aise mat uda.",
  "Overtime kiya tha is paise ke liye. Yaad hai?",
  "Appraisal abhi aaya nahi, kharcha already promote ho gaya.",
  "Increment ke saath kharcha bhi increment. Net result: same.",
  "Payday tera festival hai. Aur yahan roz manaya jaata hai.",
  "Month-end tujhe dhoondh raha hai. Chhup ja.",
  "15 tareekh aur ye haal? Baaki 15 din kaun chalayega?",
  "Mahina lamba hai, paisa chhota. Physics nahi badlegi.",
  "Abhi se aisa, toh 30 tareekh ko kya? Maggi ka dabba?",
  "Pehle save, phir jo bache woh kharch. Yahan ulta formula chal raha hai.",
  "Salary slip aur bank statement ek hi insaan ke hain? Yakeen nahi hota.",
  "CTC mein 'C' ka matlab 'Chala Gaya' toh nahi?",

  // Weekend
  "Weekend ki yaadein free hain. Weekend ka bill nahi.",
  "Friday night ka josh, Monday ka balance.",
  "Weekend pe budget ki chhutti nahi hoti.",
  "Saturday party, Sunday pachhtawa, Monday Flow ka roast.",
  "Har weekend trip? Travel blogger hai kya?",
  "Goa plan cancel. Budget ne veto kar diya.",
  "Sunday ko ghar pe reh. Wallet ko bhi weekend chahiye.",
  "'Chal na yaar, ek baar' — ye 'ek baar' har hafte aata hai.",
  "Bill split kar. Sabka sponsor mat ban.",
  "Har birthday pe treat tere hi naam kyun hoti hai? Dost smart hain.",
  "Brunch, shopping, dinner. Weekend tha ya shaadi?",
  "Weekend ka plan sasta bana. Park abhi bhi free hai.",
  "Movie + popcorn = ₹900. Ghar pe = ₹0. Bas keh raha hoon.",
  "Dost ne bola 'treat de', tune de di. Usne last kab di thi?",
  "Cab ke paison mein metro ka monthly pass aa jaata.",
  "Party ka asli guest kaun tha — tu ya tera card?",
  "Weekend khatam. Budget bhi.",

  // Family / desi
  "Chai pe charcha free hai. Cafe pe charcha ₹600 ki.",
  "Mummy ko pata chala toh chappal flying mode mein aayegi.",
  "Papa ka dialogue ready hai: 'Paise ped pe ugte hain?'",
  "'Kitne ka liya?' — mummy ka sawaal. Jhooth ready rakh.",
  "Sharma ji ke bachche SIP kar rahe hain. Yahan SIP ka matlab chai ki chuski hai.",
  "Rishtedaar poochenge 'kitna save kiya?' Jawab ready hai?",
  "Dadi kehti thi chaadar dekh ke pair phaila. Yahan nayi chaadarein aa rahi hain.",
  "Papa ne itne mein poora mahina chalaya tha. Chaar logon ka.",
  "Mummy ki gullak mein tere account se zyada paise hain.",
  "Dhaniya free mangne wala aaj online full MRP de raha hai?",
  "Sabziwale se ₹5 ka mol-bhaav, online ₹500 bina soche. Wah.",
  "Jugaad nation se ho aur full price? Sharam.",
  "Diwali abhi door hai, aur yahan already dhamaka ho raha hai.",
  "Shaadi ka season nahi hai, phir bhi naya kurta?",
  "Nimbu-mirchi wallet pe laga le. Nazar lag gayi hai.",
  "Tere stars nahi, tere kharche kharab hain.",
  "Chacha ji: 'Pehle ghar, phir car.' Tu: 'Pehle cart.'",
  "Mummy: 'Beta, khana khaya?' Tu: 'Haan, ₹600 ka.'",
  "Ye sab dekh ke Lakshmi ji bhi packing kar rahi hain.",
  "Gullak tod di? Pachhtawa bhi saath mein toota.",
  "Boond boond se sagar banta hai. Yahan balti se khaali ho raha hai.",
  "Daan-punya ka season nahi hai. Paise baantna band kar.",
  "Kuber ka khazana tere naam registered nahi hai.",

  // Tech / developer jokes
  "Tera budget abhi beta version mein hai. Bugs hi bugs.",
  "Account mein 'Error 404: Paisa not found'.",
  "Budget mein Ctrl+Z nahi hota. Sorry.",
  "Kharcha infinite loop mein hai. Break statement kahan hai?",
  "Balance: undefined. Kharcha: NaN. Flow: crashed.",
  "Budget ne 'deprecated' warning diya tha. Tune ignore kar diya.",
  "Tera spending O(n²) mein badh raha hai.",
  "Kharcha production mein bina testing ke deploy ho gaya.",
  "Bank statement mein git revert nahi hota.",
  "Tere card pe rate limiting lagani padegi.",
  "Budget ke saare unit tests fail. Ek bhi pass nahi.",
  "Tera wallet memory leak kar raha hai.",
  "Balance low-battery mode mein hai. Charger ka naam salary hai.",
  "Kharcha buffering nahi karta. Seedha 4K mein chalta hai.",
  "Budget update pending. 'Remind me later' mat daba.",
  "Tera account read-only hona chahiye.",
  "Stack overflow: kharche pe kharcha, stack pe stack.",
  "Budget ko .gitignore mein daal diya kya?",
  "Spending ka hotfix chahiye. Abhi.",
  "Wallet ko airplane mode mein daal de. Kuch din ke liye.",
  "Is kharche ka rollback plan kya hai?",
  "Budget ka CAPTCHA: 'Kya ye zaroori hai?' Tu fail.",
  "Kharche ke logs dekh ke on-call engineer bhi ro dega.",
  "Tune budget ko feature flag samjha. Off kar diya.",

  // Flow self-aware
  "Flow ne roast likha, delete kiya, phir aur tez likha.",
  "Flow saw that. 👀",
  "{name}, Flow is watching. 👀",
  "Account balance dekh ke Flow ne bhi brightness kam kar di.",
  "Main sirf ek app hoon. Par feel karta hoon.",
  "Flow ne alert diya tha. Tune 'seen' kiya.",
  "Flow roz naya roast likhta hai. Tere paas roz naya reason ready hai.",
  "Tere kharche Flow se overtime karwa rahe hain.",
  "Ye chart dekh ke Flow therapist dhoondh raha hai.",
  "Flow ke paas 365 roasts hain. Sab unlock karne ka irada hai kya?",
  "Flow: 'Budget set karo.' Tu: 'kar diya.' Uske baad? Silence.",
  "Flow ne tera kharcha analyse kiya. Result: 'Kyun?'",
  "Flow ke algorithm ne tujhe 'high-risk' tag kar diya.",
  "Main judge nahi karta. Just kidding. Karta hoon.",
  "Flow ka dil laal hai. Chart ki tarah.",
  "Flow ne pie chart banaya. Poora pie {top} kha gaya.",
  "Flow ki forecast engine bhi confuse hai — itna kaise?",
  "Kal phir aaunga. Umeed hai tab kam roast karna padega.",
  "Flow ko tujhpe shaq tha. Ab yakeen hai.",
  "Ye line likhte waqt Flow ne deep breath li.",
  "Flow ka kaam tracking hai, rona nahi. Par aaj ro liya.",
  "{name}, tu Flow ka favourite user hai. Galat reasons se.",
  "Flow ke paas data hai. Aur data jhooth nahi bolta.",
  "Main app hoon, magician nahi. Paise wapas nahi la sakta.",
  "Flow ne 'Are you sure?' button banana tha. Tere liye.",

  // Top category
  "{top} ne tera budget adopt kar liya hai. Legally.",
  "{top} ne iss month budget ko personal dushmani bana liya hai.",
  "{top} ka CEO banne ka plan hai kya?",
  "{top} pe itna? {top} walon ko ab tera naam pata hai.",
  "{top} tera sabse bada lever hai. Aur sabse zyada paisa wahin se nikal raha hai.",
  "{top} ki company ke shares le le. Dividend toh milega.",
  "{top}: 1. Budget: 0. Match abhi baaki hai.",
  "Tere expenses ka hero: {top}. Villain bhi {top}.",
  "{top} ko thoda break de. Relationship healthy rehta hai.",
  "Flow {top} category ka naam badal ke 'Problem' rakhne ki soch raha hai.",
  "{name}, {top} teri weakness hai. Flow ne note kar liya.",
  "{top} mein 20% cut = asli saving. Baaki sab timepass.",
  "{top} ka loyalty card nahi, loyalty problem hai.",

  // Financial math
  "Is kharche mein ek SIP ki installment ho jaati.",
  "Ye paisa FD mein hota toh byaaj kama raha hota. Abhi sirf yaadein kama raha hai.",
  "Is amount mein ek mahine ka Wi-Fi aa jaata. Aur Wi-Fi kaam ka hai.",
  "Compound interest ko kaam karne de. Compound kharche ko nahi.",
  "Tera kharcha inflation se tez bhaag raha hai. Olympic material.",
  "Sensex girta hai, uthta hai. Tera kharcha sirf uthta hai.",
  "₹500 roz = ₹1.8 lakh saal ka. Ab soch.",
  "Chhote kharche chhote nahi hote. Bas chupke hote hain.",
  "Ye kharcha nahi, ek chhoti si EMI hai jo tune khud ko de di.",
  "Is rate pe retirement 90 saal ki umar mein hoga. Agar hua toh.",
  "Saving ko spelling mistake samajh liya kya?",
  "Future self abhi se complaint likh raha hai. Sun.",
  "60 saal wala future self thank you nahi bolega. Guarantee.",
  "Emergency fund emergency ke liye hai. Sale emergency nahi hai.",
  "Duniya ke sabse ameer investor purani gaadi chalate hain. Tu har saal naya phone.",
  "Ameer dikhna aur ameer hona — alag subjects. Tu pehle wale mein topper.",
  "Paisa bachana bhi flex hai. Sabse underrated flex.",
  "Asli ameer chup chaap save karte hain. Yahan shor macha ke kharcha ho raha hai.",
  "Net worth aur Instagram — dono ko reality check chahiye.",

  // Absurd / unexpected
  "Tere paison pe GPS lagwana padega. Pata toh chale kahan jaate hain.",
  "Tera wallet ab witness protection mein hai.",
  "Wallet ne FIR likhwa di hai. Accused: tu.",
  "Tere paison ne resignation bheja: 'Better opportunities elsewhere.'",
  "Piggy bank ne naya ghar dhoondh liya.",
  "Paise ko bhi saans leni hoti hai. Yahan oxygen hi band hai.",
  "Bank balance hide and seek khel raha hai. Aur jeet raha hai.",
  "Wallet ka missing poster lagwana padega.",
  "Account mein ab sirf echo hai. 'Paisa... paisa... paisa...'",
  "Thanos ek chutki mein aadha le gaya. Tere kharche poora le gaye.",
  "Tera kharcha dekh ke ATM ne bhi 'Out of service' laga diya.",
  "Teri spending pe series banni chahiye. Genre: horror.",
  "GST wale tujhe Diwali card bhejenge is saal.",
  "Tax department soch raha hai itna paisa aaya kahan se. Aaya hi nahi, bas gaya.",
  "Mall wale tera birthday yaad rakhte hain. Mummy ke baad sirf wahi.",
  "Tere liye naya word banana padega: 'kharchaholic'.",
  "Tera wallet ab sirf decorative item hai.",
  "Chillar bhi darr ke gullak mein chhup gayi.",
  "Tera paisa jadugar hai. Aata hai, aur gayab.",
  "Bank ne tujhe 'Most Active Customer' award diya. Galat category mein.",
  "Tere kharche pe documentary banegi: 'Where Did It Go?'",
  "Paisa haath ka mail hota hai. Tere haath kaafi saaf hain.",

  // Fake concern
  "Sab theek hai na? Itna kharcha normal nahi hai. Flow worried hai.",
  "Paani pi. Phone neeche rakh. Deep breath. Checkout cancel.",
  "Chal, aaj sirf dekhna, khareedna nahi. Deal?",
  "Girna allowed hai. Kal se uth ke save karenge. Saath mein.",
  "Match haara hai, series nahi. Kal comeback.",
  "Abhi bhi time hai. Mahina khatam nahi hua, tu bhi nahi.",
  "Ek no-spend day try kar. Flow cheer karega.",
  "Kal tujhe aaj ka ye decision thank you bolega. Agar abhi ruk jaaye toh.",
  "Bura mat maan. Flow tera dost hai. Bas mooh-phat hai.",
  "Roast isliye karta hoon kyunki care karta hoon. Thoda sa.",
  "Aaj ka mantra: 'Nahi chahiye.' Sabse sasta word hai.",
  "Wishlist bana, 30 din ruk. Aadhi cheezein khud delete ho jayengi.",
  "Pehle purana use kar, phir naya. Radical idea, pata hai.",
  "Repair bhi option hai. Sirf replace nahi.",

  // Cricket / Bollywood
  "Budget Test match hai, T20 nahi. Har ball pe chhakka mat maar.",
  "Required run rate dekh — budget ko ab miracle chahiye.",
  "Third umpire bhi bolega: OUT. Budget se bahar.",
  "Powerplay khatam. Ab sambhal ke khel.",
  "Captain cool ban. Har over mein paisa finish mat kar.",
  "Free hit nahi hai. Har kharcha scoreboard pe dikhta hai.",
  "'Picture abhi baaki hai' — aur mahina bhi.",
  "'Kitne aadmi the?' Nahi — kitne kharche the?",
  "Mogambo khush hua? Nahi. Bank dukhi hua.",
  "'All is well' bolne se balance well nahi hota.",
  "Ek chutki saving ki keemat tum kya jaano.",
  "Ye film nahi jahan har scene mein paise udaaye jaayein. Budget hi director hai.",
  "Is mahine ka villain koi aur nahi. Aaina dekh.",
  "Rishte mein toh hum tumhare budget lagte hain. Izzat do.",

  // Ambani / rich
  "Ambani banne ka plan hai kya? Pehle Ambani jitna kama toh le.",
  "Billionaire wali harkatein, thousandaire wala account.",
  "Private jet ke sapne, local train ka pass. Balance kar.",
  "Antilia nahi, 1BHK ka kiraya yaad rakh.",
  "Forbes list mein naam nahi hai. Relax.",
  "Ambani ke ghar ki shaadi nahi hai. Simple reh.",
  "Tata-Birla wali lifestyle, EMI wala bank statement.",
  "Tu rich nahi, 'rich-looking' hai. Aur woh zyada mehnga hai.",

  // Short and punchy
  "Interesting decision.",
  "Noted. Judging.",
  "Yeah... we're not doing this.",
  "Your wallet called. It's not okay.",
  "Who approved this?",
  "Respectfully, no.",
  "Okay genius. Ab kya?",
  "Be honest. Zaroori tha?",
  "Flow has questions. And receipts.",
  "Explain yourself. Detail mein.",
  "Kal milte hain. Kam kharche ke saath, umeed hai.",
];

// Level: mild — only today's allowance is crossed. Cheeky, a raised eyebrow.
export const MILD_ROASTS = [
  "Aaj ka allowance thoda sa cross. Thoda sa. Flow noticed. 👀",
  "{over} extra aaj. Kal thoda sambhal lena, deal?",
  "Aaj ka quota khatam. Baaki din sirf paani aur willpower.",
  "Allowance ne 'bas' bola tha. Tune 'thoda aur' sun liya.",
  "{over} upar. Warning hai, FIR nahi. Abhi.",
  "Aaj thoda zyada ho gaya. Kal isko fix karna hai. Hopefully.",
  "Allowance crossed. Flow ne eyebrow uthayi hai. Sirf ek.",
  "Aaj ka budget over, month ka nahi. Abhi bhi time hai, champ.",
  "{over} ki chhoti si galti. Chhoti galtiyan hi badi banti hain.",
  "Today: 0. Kharcha: 1. Kal rematch.",
  "Aaj {top} jeet gaya. Kal tu jeetna.",
  "Ek din ka slip. Streak nahi tootni chahiye thi, par chalo.",
  "Aaj ke liye card ko sula de. Good night, card.",
  "Allowance cross karna itna easy tha? Flow ko laga tha tu tough hai.",
  "Aaj ka roast light hai. Kal ka depend karta hai tujh pe.",
  "{over} extra. Kal ki chai ghar pe, samjha?",
  "Chhota sa overspend. Flow ne note kiya, dil pe nahi liya. Abhi.",
  "Aaj thoda upar. Kal thoda neeche. Maths barabar.",
  "Aaj ka limit gaya. Ab sirf window shopping allowed hai.",
  "Pehla warning. Flow polite hai. Zyada din nahi rahega.",
  "Aaj ka kharcha aaj ki kahani. Kal nayi kahani likh.",
  "{name}, aaj thoda slip hua. Uth ja, kal se wapas.",
  "Allowance: crossed. Month: still alive. Chill, par sambhal.",
  "Aaj ke baad kuch bhi kharcha = extra roast. Choice teri.",
  "Soft warning: Flow ab bhi achha dost hai. Kal tak.",
  "Aaj ek kadam budget se aage. Kal do kadam peeche aa.",
  "Aaj ka score thoda laal. Kal hara karna hai.",
  "Mild overspend detected. Spicy roast pending.",
  "Aaj bas itna hi. Wallet ko goodnight bol.",
  "{over} aaj extra. Chhota number, bada lesson.",
];

// Level: inferno — budget blown by 20% or more. Full savage, still no abuse.
export const INFERNO_ROASTS = [
  "{over} over. Budget ab budget nahi, crime scene hai. 💀",
  "Flow ne budget ka funeral arrange kar diya hai. Tu chief guest hai.",
  "{over} upar. Calculator ne resign kiya, Excel ne desh chhod diya.",
  "Ye overspend nahi, full-blown heist hai. Aur victim tu khud hai.",
  "Budget ko RIP. Cause of death: {top}.",
  "{over} over. Ab toh Flow bhi bolne se darr raha hai.",
  "Congratulations, tune budget ko ek myth bana diya.",
  "Is level pe roast nahi, intervention chahiye.",
  "{over} extra. Mummy ko Flow bataye, ya khud confess karna hai?",
  "Budget: dead. Wallet: ICU. Tu: shopping app pe.",
  "Tune budget cross nahi kiya, uski izzat ka dahan kar diya.",
  "{over} upar. Ab ye 'overspending' nahi, 'lifestyle choice' hai.",
  "Flow ki red colour bhi kam pad gayi. Black mode on. 💀",
  "Is mahine ka kharcha dekh ke agla mahina bhi dar gaya.",
  "{top} ne tera budget kha liya, bones bhi nahi chhodi.",
  "{over} over. Ab bas ek hi option: no-spend till month-end.",
  "Tera budget Titanic tha. Aur {top} iceberg.",
  "Ye chart nahi, rocket launch hai. Seedha budget ke bahar.",
  "{over} extra. Flow ne tera naam 'Big Spender Hall of Fame' mein daal diya.",
  "Budget ne white flag dikha diya. Aur attack phir bhi jaari hai.",
  "{name}, ye kya kar diya? Flow ko baithna padega.",
  "{over} upar. Ab agle mahine ka budget bhi darr ke chhup gaya.",
  "Level: Final Boss. Wallet ke paas health bar hi nahi bachi.",
  "Is overspend pe documentary banegi. Title: 'Why, {bro}, why?'",
  "{over} over. Ab toh gullak bhi resign kar rahi hai.",
  "Budget toh gaya. Ab dignity bachate hain. Card neeche rakh.",
  "Ye overspending ka world record attempt tha kya?",
  "{over} extra. Flow ne SOS bhej diya hai. Tere wallet ki taraf se.",
  "Mahina khatam nahi hua, budget kab ka khatam. Legendary.",
  "Emergency meeting: tu, Flow aur tera bank balance. Abhi.",
];

export const BUDGET_PRAISE = [
  "{streak} days under budget. Character development.",
  "{streak} days under budget. Suspicious. Kaun ho tum?",
  "No roast today. Tumne actually control kar liya. 😐",
  "Aaj budget mein ho. Screenshot le lo, rare moment hai.",
  "Wallet safe. Flow ko tum par shaq ho raha hai.",
  "Budget ke andar? {Bro}, character development!",
  "{streak} din ki streak. Flow ke roasts unemployed ho gaye.",
  "Flow roast likh ke baitha tha. Tune mauka hi nahi diya.",
  "{name}, ye tu hi hai na? Ya kisi aur ne phone le liya?",
  "Budget intact. Mummy proud, bank proud, Flow thoda confused.",
  "{streak} din se control. Aadat ban rahi hai. Dangerous.",
  "Wallet ne aaj pehli baar smile kiya.",
  "Ye streak mat todna. Flow ne popcorn le rakha hai.",
  "Zero drama, zero overspend. Boring. Perfect.",
  "{top} bhi control mein hai. Kya hua tujhe?",
  "Sharma ji ka beta ab tujhse tips le raha hai.",
  "{streak} days. Budget ne tujhe friend request bheji hai.",
  "Aaj ka roast cancelled. Reason: achha behaviour.",
  "Financial glow-up in progress. {streak} din se.",
  "Flow ko aaj kuch kehne ko nahi mila. Ye compliment hai.",
  "Tu budget ke andar hai aur Flow ko adjust karne mein time lag raha hai.",
  "Test match wali batting. Tuk tuk, par wicket nahi gira.",
  "Captain cool finish. {streak} din se.",
  "Future self high-five de raha hai. Accept kar.",
  "Compound interest tujhe dekh ke muskura raha hai.",
  "{name}, discipline ka naya brand ambassador.",
  "Budget: safe. Tu: surprisingly responsible. Flow: 😐",
  "Wallet ka BP normal hai. Aise hi rakh.",
  "{streak} din bina drama. Netflix pe release kar dein?",
  "Aaj khush ho ja. Kal phir check karunga. 👀",
  "Character arc complete? Nahi, abhi {streak} din hi hue. Chalta reh.",
];

export function dailyNudge(list: string[], seed: string, vars: Record<string, string>, now = new Date()) {
  const day = Math.floor((new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime() - new Date(now.getFullYear(), 0, 1).getTime()) / 86_400_000);
  let hash = 0;
  for (const char of seed) hash = (hash * 31 + char.charCodeAt(0)) >>> 0;
  return list[(day + hash) % list.length].replace(/\{(\w+)\}/g, (_, key: string) => vars[key] ?? "");
}
