// Daily Hinglish nudges. One line per day of the year, rotated per user so a whole year passes without a repeat.
// Placeholders: {name} first name, {over} amount over the limit, {top} biggest category, {streak} days on budget.

export const BUDGET_ROASTS = [
  "Bhai kam kharcha kar, paisa ped pe nahi ugta.",
  "Bhai rukja! Wallet ro raha hai.",
  "Bhai pagal hai kya? Ambani ban raha hai kya?",
  "Bas kar bhai, budget ne resign kar diya hai.",
  "Bhai, itna kharcha? Ambani bhi ek baar soch lete.",
  "Rukja bhai, card ko thoda aaram de.",
  "Bhai tu kharch raha hai ya charity kar raha hai?",
  "Bhai, budget ki izzat kar, woh bhi kisi ka budget hai.",
  "Oye! Paise ko thoda saans lene de.",
  "Bhai, UPI PIN bhool ja kuch din ke liye.",
  "Bhai, month-end abhi door hai. Aaram se!",
  "Itna swipe toh dating app pe bhi nahi karte bhai.",
  "Bhai, Ambani ka beta nahi hai tu. Yaad rakh.",
  "Kharcha kam, sapne zyada. Chal bhai.",
  "Bhai, bank balance dekh ke dil baith gaya.",
  "Bhai, budget banata kyun hai agar todna hi hai?",
  "Wallet ka message aaya hai: 'Bhai mujhe chhod de.'",
  "Bhai, EMI wale uncle aa rahe hain, sambhal ja.",
  "Bhai rukja, Diwali abhi nahi aayi.",
  "Kya scene hai bhai? Lottery lagi hai kya?",
  "Bhai, ek din 'No Spend Day' bhi hota hai.",
  "Bhai, Swiggy ko tera address zabaani yaad ho gaya hai.",
  "Delivery wala bhaiya ab family member lagta hai.",
  "Bhai, ghar ka khana bhi khana hota hai.",
  "Bhai, Maggi bana le, 2 minute mein budget bachega.",
  "Bhai, itna order karega toh delivery boy ko rakhi baandhni padegi.",
  "Bhai, chai tapri pe jaa, cafe ka bill mat bana.",
  "₹300 ki coffee? Bhai tu coffee company ka shareholder hai kya?",
  "Bhai, dal chawal mein bhi swaad hai. Try kar.",
  "Bhai, fridge khol pehle, app baad mein.",
  "Bhai, cart mein daal, checkout mat kar.",
  "Courier wala tujhe naam se jaanta hai bhai. Soch.",
  "Bhai, sale hai toh zaroori nahi ki khareedna hai.",
  "Big sale roz nahi hoti bhai, par tu roz khareedta hai.",
  "Bhai, ek aur t-shirt? Almirah bhi bol raha 'bas kar'.",
  "Bhai, 'Add to cart' tera cardio ban gaya hai.",
  "Bhai, jo cheez 3 din mein bhool jayega, woh mat le.",
  "Bhai, discount ke chakkar mein poora paisa gaya.",
  "Bhai, joote pe joote? Tu centipede hai kya?",
  "Bhai, gadget naya, balance purana — chalega nahi.",
  "Mummy ko pata chala toh chappal padegi, bhai.",
  "Papa bolenge: 'Paise ped pe ugte hain kya?' — sach mein nahi ugte.",
  "Bhai, mummy ke 'kitne ka liya?' ka jawab ready rakh.",
  "Bhai, Papa ki savings yaad kar, sharam aa jayegi.",
  "Bhai, dadi bolti thi — chaadar dekh ke pair phaila.",
  "Bhai, Sharma ji ka beta save kar raha hai, aur tu?",
  "Bhai, rishtedaar poochenge 'kitna save kiya?' — kya bolega?",
  "Mummy: 'Beta, gullak toda kya?' Bhai sach bata.",
  "Bhai, ghar wale paise jod rahe hain, tu udaa raha hai.",
  "Bhai, Papa ne itne mein poora mahina chalaya tha.",
  "Bhai, credit card free money nahi hai, bill aayega.",
  "Bhai, 'Buy now, pay later' ka 'later' aa raha hai.",
  "Bhai, EMI pe EMI? Tu EMI ka Ambani hai.",
  "Credit limit target nahi hai bhai, limit hai.",
  "Bhai, minimum due bharke khush mat ho.",
  "Bhai, bank ka SMS padh le, 'balance low' likha hai.",
  "Bhai, account mein utna hi bacha hai jitna chai ke liye chahiye.",
  "Bhai, salary aayi nahi, udd bhi gayi?",
  "Bhai, salary ko thoda account mein rukne de.",
  "Salary: aayi. Dekhi. Chali gayi. Bhai kya kar raha hai?",
  "Bhai, budget Test match hai, T20 nahi.",
  "Bhai, har ball pe chakka nahi maarte. Thoda defend kar.",
  "Bhai, run rate zyada hai, wicket (wallet) gir jayega.",
  "Captain cool ban bhai, har over mein paisa finish mat kar.",
  "Bhai, required run rate budget ka dekh — tension hai.",
  "Bhai, free hit nahi hai ye, har kharcha count hota hai.",
  "Bhai, Test cricket jaisa khel — tuk tuk, par tikau.",
  "Bhai, over-spending ka no-ball ho gaya.",
  "Third umpire bhi bolega: OUT! Budget se bahar.",
  "Bhai, powerplay khatam, ab sambhal ke khel.",
  "Bhai, wallet ke aansu dekh, dil pighla de.",
  "Bhai, 'Picture abhi baaki hai' — mahina abhi baaki hai.",
  "Bhai, 'Kitne aadmi the?' Nahi — kitne kharche the?",
  "Bhai, Mogambo khush hua? Nahi. Bank dukhi hua.",
  "Bhai, ye 'Kabhi Khushi Kabhie Gham' wala budget hai.",
  "Bhai, Don ko pakadna mushkil hai — tere kharche ko bhi.",
  "Bhai, tu hero nahi hai jo har scene mein paisa udaaye.",
  "Bhai, rishte mein toh hum tumhare budget lagte hain.",
  "Bhai, ek chutki saving ki keemat tum kya jaano?",
  "Bhai, 'All is well' bol ke kharcha mat kar.",
  "Bhai, {over} upar chala gaya. Ab toh ruk ja.",
  "Bhai, Bollywood ki shaadi nahi hai, simple reh.",
  "Bhai, crypto se pehle apna budget stable kar.",
  "Bhai, 'to the moon' tera kharcha ja raha hai, portfolio nahi.",
  "Bhai, market girta hai, tera kharcha kyun nahi girta?",
  "Bhai, SIP chhod ke shopping? Future tujhe maaf nahi karega.",
  "Bhai, compound interest ko kaam karne de, compound kharcha nahi.",
  "Bhai, gym ki membership li hai toh jaa bhi, paisa waste mat kar.",
  "Bhai, subscription itne hain ki OTT wale bhi confuse hain.",
  "Bhai, OTT pe OTT? Dekhne ka time kab hai?",
  "Bhai, 5 apps ka subscription, dekhta ek hi hai.",
  "Bhai, free trial cancel karna bhool gaya na?",
  "Bhai, auto-debit ne phir se hamla kiya.",
  "Bhai, cab chhod, thoda paidal bhi chal.",
  "Bhai, metro bhi comfortable hai, try kar.",
  "Bhai, petrol ki keemat pata hai? Phir bhi ghoom raha hai.",
  "Bhai, weekend trip har weekend nahi hota.",
  "Bhai, Goa plan cancel. Budget ne bola 'no'.",
  "Bhai, Manali baad mein, pehle balance sambhal.",
  "Bhai, party tu de raha hai ya party tera wallet le rahi hai?",
  "Bhai, dost 'treat de' bolenge, tu 'budget hai' bol.",
  "Bhai, har birthday pe tu hi bill kyun bharta hai?",
  "Bhai, 'Aaj mera treat' — roz nahi hota.",
  "Bhai, split kar bill, hero mat ban.",
  "Bhai, hisaab app pe kar, dil pe nahi.",
  "Bhai, {top} pe itna kharcha? Tu {top} ka CEO hai kya?",
  "Bhai, pyaar free hai, date ka bill nahi.",
  "Bhai, gift se zyada time de, sasta padega.",
  "Bhai, Valentine's Day roz nahi hota.",
  "Bhai, shaadi ka season tere wallet ka dushman hai.",
  "Bhai, har shaadi mein naya kurta zaroori nahi.",
  "Bhai, lifafa chhota rakh, budget bada.",
  "Bhai, festival hai, kharcha nahi khushiyan baant.",
  "Bhai, Diwali ki safai kar, wallet ki nahi.",
  "Bhai, Holi mein rang ud rahe hain, tere paise bhi.",
  "Bhai, Navratri mein garba kar, shopping nahi.",
  "Bhai, Rakhi pe behen ko de, baaki pe control.",
  "Bhai, New Year resolution tha 'save karna' — yaad hai?",
  "Bhai, January ka josh December tak rakh.",
  "Bhai, month ke pehle hafte mein hi month khatam?",
  "Bhai, 15 tareekh aur ye haal?",
  "Bhai, month-end tujhe dhoondh raha hai.",
  "Bhai, abhi se aisa toh 30 tareekh ko kya karega?",
  "Bhai, mahina lamba hai, paisa chhota.",
  "Bhai, rukja. Saans le. Soch. Phir mat khareed.",
  "Bhai, 24 ghante ka rule: kal tak ruk, phir dekh.",
  "Bhai, zaroorat hai ya shauk? Pehle decide kar.",
  "Bhai, 'need' aur 'want' mein fark samajh.",
  "Bhai, khareedne se pehle 3 baar soch, 4th baar mat khareed.",
  "Bhai, jo nahi khareeda, woh bhi saving hai.",
  "Bhai, har 'deal' deal nahi hoti.",
  "Bhai, 'limited offer' har hafte aata hai, ruk ja.",
  "Bhai, notification off kar, sale ke message tujhe bigaad rahe hain.",
  "Bhai, shopping app uninstall kar, kuch din ke liye.",
  "Bhai, tu budget ka Thanos hai — ek chutki aur sab gaya.",
  "Bhai, Iron Man nahi hai tu, Stark Industries tere paas nahi hai.",
  "Bhai, Batman ke paas paisa hai, tere paas budget.",
  "Bhai, 'Sorry Shaktimaan' bol aur ruk ja.",
  "Bhai, superhero ban, super-spender nahi.",
  "Bhai, tera wallet 'Endgame' mein pahunch gaya hai.",
  "Bhai, ye kharcha web series ki tarah khatam hi nahi ho raha.",
  "Bhai, 'Winter is coming' — aur tera balance freeze ho raha hai.",
  "Bhai, budget koi jaadu ki chhadi nahi hai.",
  "Bhai, Money Heist tu khud pe hi kar raha hai.",
  "Bhai, Squid Game mein bhi itna paisa nahi udta.",
  "Bhai, Scam 1992 dekh ke khud pe hi scam kar raha hai kya?",
  "Bhai, 'Risk hai toh ishq hai' — budget mein nahi.",
  "Bhai, Shark Tank mein aise kharche pe sab 'I'm out' bolte.",
  "Bhai, is kharche ki valuation zero hai.",
  "Bhai, is kharche mein koi investor paisa nahi lagayega.",
  "Bhai, chill kar, har cheez 'add to cart' ke liye nahi hai.",
  "Bhai, budget ko ignore karega toh budget tujhe ignore karega.",
  "Bhai, tera balance 'low battery' mode mein hai.",
  "Bhai, wallet ko charger chahiye, aur charger salary hai.",
  "Bhai, account mein 'Error 404: Paisa not found'.",
  "Bhai, tera kharcha buffering nahi karta, seedha HD mein chalta hai.",
  "Bhai, paisa Wi-Fi nahi hai jo har jagah mile.",
  "Bhai, kharche mein Ctrl+Z nahi hota.",
  "Bhai, budget ka update install kar le.",
  "Bhai, wallet ko airplane mode mein daal de.",
  "Bhai, kharcha kam kar, warna Excel bhi rone lagega.",
  "Bhai, Flow ka chart laal ho gaya, tu bhi sharam se laal ho ja.",
  "Bhai, graph upar ja raha hai, par ye achhi baat nahi hai.",
  "Bhai, ye line budget ke upar hai. Neeche la.",
  "{name} bhai, Flow tujhe dekh raha hai. 👀",
  "Bhai, Flow ne bola hai, bas kar.",
  "Bhai, main app hoon, par mujhe bhi dukh hota hai.",
  "Bhai, maine alert diya tha. Tune suna nahi.",
  "Bhai, kal phir bolunga, par aaj toh ruk ja.",
  "Bhai, roz naya phrase, par kharcha wahi purana?",
  "Bhai, tu Raja Harishchandra nahi, sab kuch daan mat kar.",
  "Bhai, tu Karna nahi hai, daanveer mat ban.",
  "Bhai, Kuber ka khazana tere naam nahi hai.",
  "Bhai, Lakshmi ji ko jaane mat de, ghar mein rakh.",
  "Bhai, gullak tod ke kya milega? Sirf pachhtawa.",
  "Bhai, piggy bank bhi ab darr gaya hai.",
  "Bhai, gullak mein sikka daal, nikaal mat.",
  "Bhai, chillar bhi jod, crore bhi aise hi bante hain.",
  "Bhai, boond boond se sagar banta hai, aur tu sagar khaali kar raha hai.",
  "Bhai, 'Paisa bachaya, paisa kamaya' — yaad rakh.",
  "Bhai, jitni chaadar, utne pair. Aur chaadar chhoti hai.",
  "Bhai, kal ke liye bhi kuch bacha le.",
  "Bhai, future wala tu, present wale tujhe kos raha hai.",
  "Bhai, 60 saal wala tu tujhe aise thank you nahi bolega.",
  "Bhai, retirement khud nahi aati, fund karni padti hai.",
  "Bhai, emergency fund emergency ke liye hai, sale ke liye nahi.",
  "Bhai, 'YOLO' bolke mat kharch, bill bhi YOLO hi aayega.",
  "Bhai, FOMO se bach, FD mein daal.",
  "Bhai, Instagram ki life aur real life alag hai.",
  "Bhai, reel ke liye real paise mat uda.",
  "Bhai, influencer ko paisa mil raha hai, tujhe nahi.",
  "Bhai, 'link in bio' pe click mat kar.",
  "Bhai, dikhawe ka zamana hai, par EMI tujhe hi bharni hai.",
  "Bhai, naye phone se izzat nahi, balance se badhti hai.",
  "Bhai, logon ko impress karne mein khud depress mat ho.",
  "Bhai, branded ka tag hata, kaam wahi karta hai.",
  "{name}, tu Tata nahi, Birla nahi — tu budget wala banda hai.",
  "Bhai, Ambani ke ghar ki shaadi nahi hai ye.",
  "Bhai, Antilia nahi, 1BHK ka kiraya yaad rakh.",
  "Bhai, private jet nahi, local train hai tere paas.",
  "Bhai, Ambani ban raha hai kya? Pehle Ambani jitna kama toh le.",
  "Bhai, billionaire wali harkatein, thousandaire wala account.",
  "Bhai, tu Forbes list mein nahi hai, relax.",
  "Bhai, 'Paisa hi paisa hoga' — gaana hai, sach nahi.",
  "Bhai, pagal hai kya? Itna kaun kharchta hai?",
  "Bhai, dimaag ghar pe chhod ke shopping gaya tha kya?",
  "Bhai, hosh mein aa, ye tera paisa hai.",
  "Bhai, neend se uth, balance gira hua hai.",
  "Bhai, tu theek hai na? Itna kharcha normal nahi hai.",
  "Bhai, kharcha dekh ke calculator ne bhi resign kar diya.",
  "Bhai, chal ek glass paani pi, aur phone neeche rakh.",
  "Bhai, gehri saans le... aur checkout cancel kar.",
  "Bhai, meditation kar: 'Om shanti, no shopping'.",
  "Bhai, kharche ka detox kar, sirf 3 din ka.",
  "Bhai, aaj ka mantra: 'Nahi chahiye.'",
  "Bhai, 'nahi' bolna seekh, sabse sasta word hai.",
  "Bhai, tera budget tujhse zyada samajhdaar hai, uski sun.",
  "Bhai, budget banaya tha na? Kahan gaya?",
  "Bhai, budget ko 'seen' karke ignore mat kar.",
  "Bhai, budget ne tujhe 'left on read' kar diya.",
  "Bhai, budget se breakup mat kar, woh loyal hai.",
  "Bhai, budget aur tu — 'It's complicated'.",
  "Bhai, budget se pyaar kar, kharche se nahi.",
  "Bhai, is mahine ka villain tu khud hai.",
  "Bhai, tera kharcha Sensex se tez bhaag raha hai.",
  "Bhai, inflation bhi tujhse sharma rahi hai.",
  "Bhai, RBI ko bhi tere kharche ki report chahiye.",
  "Bhai, tera kharcha dekh ke GST wale khush hain.",
  "Bhai, tax department soch raha hoga itna paisa aaya kahan se.",
  "Bhai, sarkar tax leti hai, tu toh khud hi de raha hai.",
  "Bhai, dukaandar tujhe dekh ke muskurata hai. Kyun? Soch.",
  "Bhai, mall wale tujhe VIP maanne lage hain.",
  "Bhai, tu mall ka brand ambassador ban gaya hai.",
  "Bhai, sabziwale se mol-bhaav karta hai, online pe nahi?",
  "Bhai, ₹10 ke dhaniye pe bargain, ₹5000 ki jacket pe nahi?",
  "Bhai, dhaniya free mangne wala aaj ye kya kar raha hai?",
  "Bhai, 'Bhaiya thoda kam karo' online bhi bol ke dekh.",
  "Bhai, cashback ke liye ₹500 mat uda.",
  "Bhai, ₹20 cashback ke chakkar mein ₹2000 gaye.",
  "Bhai, reward points se ghar nahi chalta.",
  "Bhai, coupon ka matlab kharcha karna nahi hai.",
  "Bhai, 'free delivery' ke liye extra item mat daal.",
  "Bhai, minimum order value ek jaal hai.",
  "Bhai, 'Buy 1 Get 1' mein 1 bhi zaroori nahi tha.",
  "Bhai, combo offer tera budget combo-break kar raha hai.",
  "Bhai, late night shopping band. Raat ko dimaag kam chalta hai.",
  "Bhai, raat 2 baje cart bhara? Classic.",
  "Bhai, bore ho raha hai toh kitaab padh, shopping nahi.",
  "Bhai, dukh mein shopping, sukh mein shopping — bas bhi kar.",
  "Bhai, retail therapy se real therapy sasti padegi.",
  "Bhai, stress ka ilaaj kharcha nahi, walk hai.",
  "Bhai, Sunday ko ghar pe reh, wallet bhi rest karega.",
  "Bhai, weekend pe bhi budget ki chhutti nahi hoti.",
  "Bhai, Friday night ka josh, Monday ka balance.",
  "Bhai, 'Chal na yaar, ek baar' — yahi toh problem hai.",
  "Bhai, 'last time' tune pichhle 10 baar bola tha.",
  "Bhai, 'kal se pakka' — kal kabhi nahi aata.",
  "Bhai, excuse kam, saving zyada.",
  "Bhai, 'deserve karta hoon' — haan, par budget bhi deserve karta hai.",
  "Bhai, treat yourself ka matlab roz treat nahi.",
  "Bhai, self-love mein thoda self-control bhi aata hai.",
  "Bhai, kharche ki speed pe challan katna chahiye.",
  "Bhai, apne card pe speed breaker laga de.",
  "Bhai, brake maar, aage budget ka khadda hai.",
  "Bhai, gaadi dheere chala, kharcha bhi.",
  "Bhai, 'dheere chalo, surakshit chalo' — paise pe bhi lagu.",
  "Bhai, signal laal hai. Ruk ja.",
  "Bhai, ye mahina marathon hai. Stamina bacha.",
  "Bhai, sprint mat maar, mahina lamba hai.",
  "Bhai, nal band kar, paisa tapak raha hai.",
  "Bhai, wallet mein chhed hai kya?",
  "Bhai, jeb mein chhed ho gaya lagta hai.",
  "Bhai, paisa paani ki tarah beh raha hai — aur paani bhi mehnga hai.",
  "Bhai, kanjoos mat ban, par itna daanveer bhi mat ban.",
  "Bhai, beech ka raasta pakad — na kanjoos, na Kuber.",
  "Bhai, balance sirf yoga mein nahi, account mein bhi chahiye.",
  "Bhai, budget ki kasam kha, aur tod mat.",
  "Bhai, ek kaam kar — aaj sirf dekh, khareed mat.",
  "Bhai, window shopping kar, window pe hi ruk.",
  "Bhai, wishlist bana, cart nahi.",
  "Bhai, wishlist mein 30 din rakh, phir dekh chahiye ki nahi.",
  "Bhai, ghar mein kitni cheezein hain jo use nahi karta? Gin le.",
  "Bhai, pehle purana use kar, phir naya le.",
  "Bhai, 'repair' bhi ek option hota hai, sirf 'replace' nahi.",
  "Bhai, jugaad kar, Indian hai tu.",
  "Bhai, jugaad se kaam chala, card se nahi.",
  "Bhai, desi ghee jaisa budget rakh — thoda, par kaafi.",
  "Bhai, nimbu-mirchi laga le wallet pe, nazar lag gayi hai.",
  "Bhai, kisi ne tere wallet pe kaala jaadu kiya hai kya?",
  "Bhai, jyotishi ne bhi bola hai — is mahine kharcha mat kar.",
  "Bhai, tere stars nahi, tere kharche kharab hain.",
  "Bhai, Shani ki dasha nahi, shopping ki dasha hai.",
  "Bhai, horoscope bol raha hai: 'Aaj paisa bachao'.",
  "Bhai, Monday ka motivation: kharcha zero.",
  "Bhai, Tuesday ko Hanuman ji ka naam le, aur card chhupa de.",
  "Bhai, Wednesday hai — beech hafte ka budget check kar.",
  "Bhai, Thursday aa gaya, weekend ka plan sasta bana.",
  "Bhai, Friday hai, par salary Friday nahi hai.",
  "Bhai, Saturday ko party, Sunday ko pachhtawa?",
  "Bhai, Sunday funday, par spend-nahi-day.",
  "Bhai, budget tera bhai hai, usse dhokha mat de.",
  "Bhai, budget ko bhai bol, woh tujhe bachayega.",
  "Bhai, Flow ne tera saath diya, tu Flow ka saath de.",
  "Bhai, chal Flow ke saath deal: kal kuch nahi khareedega.",
  "Bhai, aaj ka score: Kharcha 1, Budget 0. Kal badla le.",
  "Bhai, match haara hai, series nahi. Kal se sambhal.",
  "Bhai, gir gaya toh kya, uth aur save kar.",
  "Bhai, comeback bhi hota hai. Kal se kam kharcha.",
  "Bhai, abhi bhi time hai, mahina bacha hai.",
  "Bhai, 'hum honge kaamyab' — bas kharcha kam kar.",
  "Bhai, tu kar sakta hai. Bas 'Buy now' mat daba.",
  "Bhai, paisa bachana bhi ek flex hai.",
  "Bhai, asli ameer log chup chaap save karte hain.",
  "Bhai, ameer dikhna aur ameer hona alag cheez hai.",
  "Bhai, jo dikhta hai woh bikta hai — aur tu khareed leta hai.",
  "Bhai, marketing walon ka target tu hi hai.",
  "Bhai, ad dekha, khareed liya — itna easy target mat ban.",
  "Bhai, algorithm tujhe samajh gaya hai, tu algorithm ko samajh.",
  "Bhai, 'Recommended for you' matlab 'Budget against you'.",
  "Bhai, tu customer nahi, 'loyal customer' ban gaya hai. Dukh ki baat hai.",
  "Bhai, dukaan wale tujhe Diwali card bhejte honge.",
  "Bhai, delivery ke dabbon se ghar bhar gaya.",
  "Bhai, cardboard ke dabbe bech ke thoda recover kar le.",
  "Bhai, raddi wala tere dabbon se ameer ho jayega.",
  "Bhai, tu courier wale ka favourite customer hai.",
  "Bhai, OTP aaye toh ruk ke soch — sach mein chahiye?",
  "Bhai, OTP ko 'Oh The Pain' samajh.",
  "Bhai, 'Payment successful' sun ke khush mat ho.",
  "Bhai, 'Transaction declined' tera dost hai, dushman nahi.",
  "Bhai, card decline hua? Universe bhi bol raha hai ruk ja.",
  "Bhai, UPI ka 'ting' sun ke dil 'thak' karta hai.",
  "Bhai, scan karna aasan hai, kamana mushkil.",
  "Bhai, QR code dekhte hi haath kyun kaanpta hai?",
  "Bhai, 'Pay' button pe ungli rok, bas ek minute.",
  "Bhai, soch — ye kharcha kitne ghante ki mehnat hai?",
  "Bhai, ye paisa kitni meetings baith ke kamaya tha, yaad kar.",
  "Bhai, boss ki daant khaake kamaya paisa aise mat uda.",
  "Bhai, overtime kiya tha is paise ke liye, bhool gaya?",
  "Bhai, mehnat ki kamaai hai, izzat se kharch.",
  "Bhai, paisa kamane mein mahina lagta hai, udaane mein minute.",
  "Bhai, ye kharcha tera hafte bhar ka petrol tha.",
  "Bhai, is paise mein ek mahine ka Wi-Fi aa jata.",
  "Bhai, isse ek SIP ki installment ho jaati.",
  "Bhai, ye paisa FD mein hota toh byaaj de raha hota.",
  "Bhai, ye kharcha nahi, ek chhota sa investment miss hua hai.",
  "Bhai, kharcha karna easy hai, bachana art hai.",
  "Bhai, duniya ke sabse ameer investor bhi purani gaadi chalate hain.",
  "Bhai, pehle save, phir spend — ulta mat kar.",
  "Bhai, Chanakya ne bhi dhan sambhalne ko bola tha.",
  "Bhai, 'dhan hai toh sab hai' — bacha ke rakh.",
  "Bhai, 'kal kare so aaj kar' — saving ke liye, shopping ke liye nahi.",
  "Bhai, Kabira khada bazaar mein — par khareeda kuch nahi.",
  "Bhai, gyaan nahi dunga, bas budget dekh le.",
  "Bhai, lecture nahi, sirf ek request — ruk ja.",
  "Bhai, main judge nahi kar raha... thoda sa kar raha hoon.",
  "Bhai, dil pe mat le, wallet pe le.",
  "Bhai, hasna mana nahi hai, par aaj kharcha mana hai.",
  "Bhai, aaj ka quote: 'Kam kharcho, zyada jiyo.'",
  "Bhai, tu legend hai — bas kharche mein nahi, saving mein ban.",
  "Bhai, abhi ruk gaya toh kal wala tu thank you bolega.",
  "Bhai, ek din ka break le kharche se, wallet dua dega.",
  "Bhai, saal ke 365 din, aur har din yahi bolna pad raha hai?",
  "Bhai, kam kharcha kar, zyada muskura.",
  "Bhai, paisa bolta hai — aur abhi 'bachao bachao' bol raha hai.",
  "Bhai, budget bacha, bhaichaara bacha. Chal, kal milte hain.",
];

export const BUDGET_PRAISE = [
  "Shabash bhai! Budget ka asli hero tu hi hai.",
  "Bhai, kya control hai! Wallet khush hai.",
  "Bhai, {streak} din se budget mein — legend!",
  "Bhai, aise hi chal, Sharma ji ka beta bhi jal raha hai.",
  "Bhai, tu toh financial ninja nikla.",
  "Mummy proud hai bhai, aur bank bhi.",
  "Bhai, wallet ne tujhe thank you card bheja hai.",
  "Bhai, is speed se toh Ambani bhi notes lene aayenge.",
  "Bhai, budget aur tu — perfect jodi.",
  "Bhai, {streak} din ki streak! Tod mat.",
  "Bhai, aaj kharcha kam, kal sapne bade.",
  "Bhai, Dhoni wala finish — shaant aur control mein.",
  "Bhai, tera budget green hai, jaise chai ki patti.",
  "Bhai, SIP wale bhi tujhpe proud hain.",
  "Bhai, future wala tu tujhe high-five de raha hai.",
  "Bhai, tu budget ka Rahul Dravid hai — The Wall.",
  "Bhai, gullak khush, mummy khush, sab khush.",
  "Bhai, aise hi chalta raha toh mahine ke end mein party banti hai (budget mein).",
  "Bhai, {streak} din — ab toh aadat ban gayi hai!",
  "Bhai, control dekh ke calculator bhi taali baja raha hai.",
  "Bhai, tera kharcha dieting pe hai. Mast!",
  "Bhai, kamaal kar diya — budget intact.",
  "Bhai, Flow ko tujhpe garv hai.",
  "Bhai, samajhdaar banda! Aise hi chal.",
  "Bhai, aaj bhi budget ke andar — respect.",
  "Bhai, tu toh saving ka topper nikla.",
  "Bhai, compound interest tujhe dekh ke muskura raha hai.",
  "Bhai, wallet ka BP normal hai. Badhiya.",
  "Bhai, is mahine ka MVP tu hi hai.",
  "Bhai, {name} matlab discipline. Keep going!",
  "Bhai, aise hi chalte raho, Ambani wala future pakka.",
];

export function dailyNudge(list: string[], seed: string, vars: Record<string, string>, now = new Date()) {
  const day = Math.floor((new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime() - new Date(now.getFullYear(), 0, 1).getTime()) / 86_400_000);
  let hash = 0;
  for (const char of seed) hash = (hash * 31 + char.charCodeAt(0)) >>> 0;
  return list[(day + hash) % list.length].replace(/\{(\w+)\}/g, (_, key: string) => vars[key] ?? "");
}
